[package]
name = "glifrenderer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glifparser = { git = "https://github.com/MFEK/glifparser.rlib", branch = "master", features=["skia", "mfek"] }
skulpin = { version = "0.14" }
skulpin-renderer = "0.14"
log = "0.4"
font-kit = "0.10"
derive_more = "0.99"
enum-iterator = "0.7.0"